name: Build
description: Build ui and core

on:
  push:
    branches:
      - main

jobs:
  build-ui-core:
    name: Build ui and core
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 24

      - name: Install dependencies
        run: npm install

      - name: Build ui and core
        run: npm run build