name: Publish
description: Publish on Snapcraft and website on Vercel

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-snap:
    name: Build and publish snap
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 24

      - name: Install dependencies
        run: npm install

      - name: Build ui and core
        run: npm run build

      - name: Install lxd and snapcraft
        run: |
          sudo snap install lxd
          sudo lxd init --auto
          sudo iptables -P FORWARD ACCEPT
          sudo snap install snapcraft --channel=8.x/stable --classic
          sudo usermod -aG lxd $USER

      - name: Build snap
        run: sg lxd -c "npm run build:snap"

      - name: Publish to Snap Store
        run: |
          snapcraft upload ./dist/release/dist/*.snap --release stable
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}

  build-website:
    name: Build and publish website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 24

      - name: Install Vercel cli
        run: npm install -g vercel

      - name: Install dependencies
        run: npm install

      - name: Build website
        run: npm run website:build

      - name: Pull Vercel environment
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

      - name: Deploy dist folder to Vercel
        run: vercel deploy dist/website --prod --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}