name: Release
description: Create release with Linux, macOS and Windows builds

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  prepare:
    name: Set release version
    runs-on: ubuntu-latest
    outputs:
      release_notes: ${{ steps.generate_release_notes.outputs.result }}
      version: ${{ steps.read_version.outputs.version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Read version from package.json
        id: read_version
        run: |
          current_tag=$(jq -r '.version' dist/release/package.json)
          echo "current_tag=$current_tag" >> $GITHUB_ENV
          echo "version=$current_tag" >> $GITHUB_OUTPUT

      - name: Get previous tag
        run: |
          previous_tag=$(git log --tags --simplify-by-decoration --pretty="format:%D" | grep -o "tag: [^,]*" | head -n 1 | sed 's/tag: //')
          echo "previous_tag=$previous_tag" >> $GITHUB_ENV

      - name: Generate release notes
        id: generate_release_notes
        uses: actions/github-script@v9
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          result-encoding: string
          script: |
            const { owner, repo } = context.repo;
            const previousTag = process.env.previous_tag;
            const currentTag = process.env.current_tag;

            let commitList;
            if (previousTag) {
              const commits = await github.rest.repos.compareCommits({ owner, repo, base: previousTag, head: currentTag });
              // order from newest to oldest
              commitList = commits.data.commits.reverse();
            } else {
              const commits = await github.rest.repos.listCommits({ owner, repo });
              commitList = commits.data;
            }
            if (commitList.length === 0) {
              return 'Empty release';
            }

            const changelogSections = new Map([
              ['feat', '🚀'], ['perf', '🔥'], ['refactor', '🛠️'], ['style', '🎨'], ['chore', '🧹'], ['fix', '🩹'],
              ['build', '📦'], ['ci', '🔄'], ['test', '🧪'], ['docs', '📝'], ['revert', '🔙'], ['other', '']
            ]);
            const sections = {};
            for (const element of commitList) {
              if (!element.commit.message.startsWith('chore(main): release')) {
                const category = element.commit.message.split(':')[0].trim().toLowerCase();
                const commitMessage = changelogSections.get(category) ? element.commit.message.split(':')[1] : element.commit.message;
                const section = changelogSections.get(category) ? category : 'other';
                if (!sections[section]) {
                   sections[section] = [];
                }
                sections[section].push(`- ${commitMessage.trim()} ([${element.sha.substring(0, 7)}](${element.html_url}))`);
              }
            }

            let changelog = '';
            for (const section of changelogSections.keys()) {
              if (sections[section]) {
                if (changelog) changelog += '\n';
                changelog += `### ${changelogSections.get(section)} ${section.charAt(0).toUpperCase() + section.slice(1)}\n`;
                changelog += sections[section].join('\n');
              }
            }
            return changelog;
      
  build-linux:
    name: Build Linux ${{ matrix.package-type }}
    runs-on: ubuntu-latest
    needs: prepare
    strategy:
      matrix:
        package-type: [deb, rpm]
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 24

      - name: Install dependencies
        run: npm install

      - name: Build ui and core
        run: npm run build

      - name: Build deb
        if: matrix.package-type == 'deb'
        run: npm run build:deb

      - name: Install rpm build tools
        if: matrix.package-type == 'rpm'
        run: |
          sudo apt-get update
          sudo apt-get install -y rpm

      - name: Build rpm
        if: matrix.package-type == 'rpm'
        run: npm run build:rpm

      - name: Create GitHub release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ needs.prepare.outputs.version }}
          name: ${{ needs.prepare.outputs.version }}
          body: ${{ needs.prepare.outputs.release_notes }}
          files: |
            ./dist/release/dist/*.${{ matrix.package-type }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-mac:
    name: Build macOS zip and dmg
    runs-on: macos-latest
    needs: prepare
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 24

      - name: Install dependencies
        run: npm install

      - name: Build ui and core
        run: npm run build

      - name: Install Apple certificate
        uses: apple-actions/import-codesign-certs@v7
        with:
          # codesigning
          p12-file-base64: ${{ secrets.MAC_CSC_LINK }}
          p12-password: ${{ secrets.MAC_CSC_KEY_PASSWORD }}

      - name: Build zip and dmg
        run:  npm run build:mac
        env:          
          # notarization
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}

      - name: Create GitHub release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ needs.prepare.outputs.version }}
          name: ${{ needs.prepare.outputs.version }}
          body: ${{ needs.prepare.outputs.release_notes }}
          files: |
            ./dist/release/dist/*.zip
            ./dist/release/dist/*.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-windows:
    name: Build Windows exe and appx
    runs-on: windows-latest
    needs: prepare
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 24

      - name: Install dependencies
        run: npm install

      - name: Build ui and core
        run: npm run build

      - name: Build exe and appx
        run:  npm run build:win -- --config.appx.identityName="${{ secrets.APPX_IDENTITY_NAME }}" --config.appx.publisher="${{ secrets.APPX_PUBLISHER }}"

      - name: Create GitHub release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ needs.prepare.outputs.version }}
          name: ${{ needs.prepare.outputs.version }}
          body: ${{ needs.prepare.outputs.release_notes }}
          files: |
            ./dist/release/dist/*.exe
            ./dist/release/dist/*.appx
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}